<?php

    use Illuminate\Database\Seeder;
    use Carbon\Carbon;

    class codelookupsTableSeeder extends Seeder
    {
        /**
         * Run the database seeds.
         * @return void
         */
        public function run()
        {
            \App\Models\Codelookups::truncate();

            $codelookups = DB::table( 'codelookups' )->insert(
                [
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '1', 'value' => null, 'string' => 'Apparel', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '2', 'value' => null, 'string' => 'Banking', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '3', 'value' => null, 'string' => 'Biotechnology', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '4', 'value' => null, 'string' => 'Chemicals', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '5', 'value' => null, 'string' => 'Communications', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '6', 'value' => null, 'string' => 'Construction', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '7', 'value' => null, 'string' => 'Consulting', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '8', 'value' => null, 'string' => 'Education', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '9', 'value' => null, 'string' => 'Electronics', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '10', 'value' => null, 'string' => 'Energy', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '11', 'value' => null, 'string' => 'Engineering', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '12', 'value' => null, 'string' => 'Entertainment', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '13', 'value' => null, 'string' => 'Environmental', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '14', 'value' => null, 'string' => 'Finance', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '15', 'value' => null, 'string' => 'Government', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '16', 'value' => null, 'string' => 'Healthcare', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '17', 'value' => null, 'string' => 'Hospitality', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '18', 'value' => null, 'string' => 'Insurance', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '19', 'value' => null, 'string' => 'Machinery', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '20', 'value' => null, 'string' => 'Manufacturing', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '21', 'value' => null, 'string' => 'Media', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '22', 'value' => null, 'string' => 'Not for Profit', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '23', 'value' => null, 'string' => 'Retail', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '24', 'value' => null, 'string' => 'Shipping', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '25', 'value' => null, 'string' => 'Technology', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '26', 'value' => null, 'string' => 'Telecommunications', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '27', 'value' => null, 'string' => 'Transportation', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '28', 'value' => null, 'string' => 'Utilities', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '29', 'value' => null, 'string' => 'School', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'INDUSTYPE', 'description' => 'Industry Type', 'code' => '30', 'value' => null, 'string' => 'Other', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '1', 'value' => null, 'string' => 'Analyst', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '2', 'value' => null, 'string' => 'Competitor', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '3', 'value' => null, 'string' => 'Customer', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '4', 'value' => null, 'string' => 'Integrator', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '5', 'value' => null, 'string' => 'Investor', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '6', 'value' => null, 'string' => 'Partner', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '7', 'value' => null, 'string' => 'Press', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '8', 'value' => null, 'string' => 'Prospect', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '9', 'value' => null, 'string' => 'Reseller', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'ACCTTYPE', 'description' => 'Account Type', 'code' => '10', 'value' => null, 'string' => 'Other', 'value2' => null, 'string2' =>null,'binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNSTAT', 'description' => 'Campaign Status', 'code' => '1', 'value' => null, 'string' => 'Planning', 'value2' => null, 'string2' =>'Planning','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNSTAT', 'description' => 'Campaign Status', 'code' => '2', 'value' => null, 'string' => 'Active', 'value2' => null, 'string2' =>'Active','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNSTAT', 'description' => 'Campaign Status', 'code' => '3', 'value' => null, 'string' => 'Inactive', 'value2' => null, 'string2' =>'Inactive','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNSTAT', 'description' => 'Campaign Status', 'code' => '4', 'value' => null, 'string' => 'Complete', 'value2' => null, 'string2' =>'Complete','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNSTAT', 'description' => 'Campaign Status', 'code' => '5', 'value' => null, 'string' => 'In-Queue', 'value2' => null, 'string2' =>'In-Queue','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNSTAT', 'description' => 'Campaign Status', 'code' => '6', 'value' => null, 'string' => 'Sending', 'value2' => null, 'string2' =>'Sending','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNTYPE', 'description' => 'Campaign Type', 'code' => '1', 'value' => null, 'string' => 'Telesales', 'value2' => null, 'string2' =>'Telesales','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNTYPE', 'description' => 'Campaign Type', 'code' => '2', 'value' => null, 'string' => 'Mail', 'value2' => null, 'string2' =>'Mail','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNTYPE', 'description' => 'Campaign Type', 'code' => '3', 'value' => null, 'string' => 'Email', 'value2' => null, 'string2' =>'Email','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNTYPE', 'description' => 'Campaign Type', 'code' => '4', 'value' => null, 'string' => 'Print', 'value2' => null, 'string2' =>'Print','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNTYPE', 'description' => 'Campaign Type', 'code' => '5', 'value' => null, 'string' => 'Web', 'value2' => null, 'string2' =>'Web','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNTYPE', 'description' => 'Campaign Type', 'code' => '6', 'value' => null, 'string' => 'Radio', 'value2' => null, 'string2' =>'Radio','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNTYPE', 'description' => 'Campaign Type', 'code' => '7', 'value' => null, 'string' => 'Television', 'value2' => null, 'string2' =>'Television','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'CMPGNTYPE', 'description' => 'Campaign Type', 'code' => '8', 'value' => null, 'string' => 'Newsletter', 'value2' => null, 'string2' =>'Newsletter','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'IMTYPE', 'description' => 'Instant Messenger', 'code' => '1', 'value' => null, 'string' => 'Yahoo', 'value2' => null, 'string2' =>'Yahoo','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'IMTYPE', 'description' => 'Instant Messenger', 'code' => '2', 'value' => null, 'string' => 'Google', 'value2' => null, 'string2' =>'Google','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'IMTYPE', 'description' => 'Instant Messenger', 'code' => '3', 'value' => null, 'string' => 'Skype', 'value2' => null, 'string2' =>'Skype','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'IMTYPE', 'description' => 'Instant Messenger', 'code' => '4', 'value' => null, 'string' => 'Facebook', 'value2' => null, 'string2' =>'Facebook','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '1', 'value' => null, 'string' => 'Cold Call', 'value2' => null, 'string2' =>'Cold Call','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '2', 'value' => null, 'string' => 'Existing Customer', 'value2' => null, 'string2' =>'Existing Customer','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '3', 'value' => null, 'string' => 'Self Generated', 'value2' => null, 'string2' =>'Self Generated','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '4', 'value' => null, 'string' => 'Employee', 'value2' => null, 'string2' =>'Employee','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '5', 'value' => null, 'string' => 'Partner', 'value2' => null, 'string2' =>'Partner','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '6', 'value' => null, 'string' => 'Public Relations', 'value2' => null, 'string2' =>'Public Relations','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '7', 'value' => null, 'string' => 'Direct Mail', 'value2' => null, 'string2' =>'Direct Mail','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '8', 'value' => null, 'string' => 'Conference', 'value2' => null, 'string2' =>'Conference','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '9', 'value' => null, 'string' => 'Trade Show', 'value2' => null, 'string2' =>'Trade Show','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '10', 'value' => null, 'string' => 'Website', 'value2' => null, 'string2' =>'Website','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '11', 'value' => null, 'string' => 'Word of mouth', 'value2' => null, 'string2' =>'Word of mouth','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '12', 'value' => null, 'string' => 'Email', 'value2' => null, 'string2' =>'Email','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '13', 'value' => null, 'string' => 'Campaign', 'value2' => null, 'string2' =>'Campaign','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
                    [ 'typename' => 'LEADSOURCE', 'description' => 'Lead Source', 'code' => '14', 'value' => null, 'string' => 'Other', 'value2' => null, 'string2' =>'Other','binary' => null,'memo' => null,'bool' => null,'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
                ]
            );
        }
    }