<?php
/**
 * Created by PhpStorm.
 * User: ITS-Gelo
 * Date: 5/24/2016
 * Time: 10:18 AM
 */
namespace App\Providers;

class EntrustCustomServiceProvider extends \Zizaco\Entrust\EntrustServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // Register blade directives
        $this->bladeDirectives();
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

    }

    /**
     * Register the blade directives
     *
     * @return void
     */
    public function bladeDirectives()
    {
        //Call to Entrust::hasRole
        \Blade::directive('role', function($expression){
            return "<?php if(\\Entrust::hasRole{$expression}) : ?>";
        });

        \Blade::directive('endrole', function($expression)
        {
            return "<?php endif; // Entrust::hasRole ?>";
        });
        // Call to Entrust::can
        \Blade::directive('permission', function($expression)
        {
            return "<?php if (\\Entrust::can{$expression}) : ?>";
        });
        \Blade::directive('endpermission', function($expression)
        {
            return "<?php endif; // Entrust::can  ?>";
        });

        // Call to Entrust::ability
        \Blade::directive('ability', function($expression)
        {
            return "<?php if(\\Entrust::ability{$expression}) : ?>";
        });

        \Blade::directive('endability', function($expression)
        {
            return "<?php endif; // Entrust::ability ?>";
        });

        return response(view('errors.403'));
    }
}